#!/bin/bash

################################################################################
# generic local build script for epics-containers repositories                 #
################################################################################

set -e

# set EPICS_TARGET_ARCH to rtems for RTEMS based targets
T_A=${EPICS_TARGET_ARCH:-linux_x86_64}
# set TARGET to runtime for runtime images
TARGET=${TARGET:-developer}
# set TAG to override the default tag
TAG=${TAG:-ec_test}

if [[ ${T_A} != "linux_x86_64" ]]; then
    # container image extension is the lcase of EPICS_TARGET_ARCH
    IMAGE_EXT=-"${T_A,,}"
fi

cd $(dirname ${0})

# make sure the ioc binaries and config symlink are cleaned up
git clean -fdx ioc

if podman version &> /dev/null && [[ -z $USE_DOCKER ]]
    then docker=podman
    else docker=docker
fi

if $docker buildx version &>/dev/null; then buildx=buildx; load=--load ; fi
if [[ $DOCKER_BUILDKIT == "0" ]]; then buildx=; load=; fi

# make sure new repos get their submodule ibek-support
if [ ! -d ibek-support/_global ] ; then git submodule update --init ; fi

# build and developer images
set -x
$docker $buildx build -t ${TAG} "${@}" $load \
    --build-arg IMAGE_EXT=$IMAGE_EXT \
    $runtime --target $TARGET .
