name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  example:
    needs: check
    if: github.ref_name == 'main'
    uses: ./.github/workflows/_example.yml
    secrets:
      EXAMPLE_DEPLOY_KEY: ${{ secrets.EXAMPLE_DEPLOY_KEY }}
